// <auto-generated />
using System;
using MAIHealthCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAIHealthCoach.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625064632_AddWaterLog")]
    partial class AddWaterLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAIHealthCoach.Domain.Coaching.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("IX_Conversations_UserId_UpdatedAt");

                    b.ToTable("Conversations", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Coaching.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CoachMessages_UserId");

                    b.HasIndex("ConversationId", "Sequence")
                        .HasDatabaseName("IX_CoachMessages_ConversationId_Sequence");

                    b.ToTable("CoachMessages", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Diary.DiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<Guid>("ServingSizeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("ServingSizeId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DiaryEntries_UserId");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("IX_DiaryEntries_UserId_Date");

                    b.ToTable("DiaryEntries", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Brand")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_FoodItems_Barcode");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_FoodItems_CreatedByUserId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FoodItems_Name");

                    b.ToTable("FoodItems", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.ServingSize", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GramsEquivalent")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId")
                        .HasDatabaseName("IX_ServingSizes_FoodItemId");

                    b.ToTable("ServingSizes", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.UserFavoriteFood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserId", "FoodItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserFavoriteFoods_UserId_FoodItemId");

                    b.ToTable("UserFavoriteFoods", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Goals.UserGoalTargets", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CaloriesKcal")
                        .HasColumnType("integer");

                    b.Property<int?>("CarbohydrateGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FatGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastOverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProteinGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WaterMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserGoalTargets_UserId");

                    b.ToTable("UserGoalTargets", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("PrimaryGoal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Metric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfiles_UserId");

                    b.ToTable("UserProfiles", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.WeightMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "MeasuredAt")
                        .HasDatabaseName("IX_WeightMeasurements_UserProfileId_MeasuredAt");

                    b.ToTable("WeightMeasurements", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_ClerkUserId");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Water.WaterLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AmountMl")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WaterLogEntries_UserId");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("IX_WaterLogEntries_UserId_Date");

                    b.ToTable("WaterLogEntries", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Coaching.Conversation", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Conversations_Users_UserId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Coaching.Message", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Coaching.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CoachMessages_Conversations_ConversationId");

                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CoachMessages_Users_UserId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Diary.DiaryEntry", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Food.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DiaryEntries_FoodItems_FoodItemId");

                    b.HasOne("MAIHealthCoach.Domain.Food.ServingSize", "ServingSize")
                        .WithMany()
                        .HasForeignKey("ServingSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DiaryEntries_ServingSizes_ServingSizeId");

                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DiaryEntries_Users_UserId");

                    b.Navigation("FoodItem");

                    b.Navigation("ServingSize");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.FoodItem", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FoodItems_Users_CreatedByUserId");

                    b.OwnsOne("MAIHealthCoach.Domain.Food.NutritionFacts", "NutritionPer100g", b1 =>
                        {
                            b1.Property<Guid>("FoodItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CarbohydrateG")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("Nutrition_CarbohydrateG");

                            b1.Property<decimal>("EnergyKcal")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("Nutrition_EnergyKcal");

                            b1.Property<decimal>("FatG")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("Nutrition_FatG");

                            b1.Property<decimal?>("FiberG")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("Nutrition_FiberG");

                            b1.Property<decimal>("ProteinG")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("Nutrition_ProteinG");

                            b1.Property<decimal?>("SaturatedFatG")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("Nutrition_SaturatedFatG");

                            b1.Property<decimal?>("SodiumMg")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_SodiumMg");

                            b1.Property<decimal?>("SugarsG")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("Nutrition_SugarsG");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("FoodItems", "public");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("NutritionPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.ServingSize", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Food.FoodItem", null)
                        .WithMany("ServingSizes")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServingSizes_FoodItems_FoodItemId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.UserFavoriteFood", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Food.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserFavoriteFoods_FoodItems_FoodItemId");

                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserFavoriteFoods_Users_UserId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Goals.UserGoalTargets", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("MAIHealthCoach.Domain.Goals.UserGoalTargets", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGoalTargets_Users_UserId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.UserProfile", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("MAIHealthCoach.Domain.UserProfiles.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfiles_Users_UserId");

                    b.OwnsOne("MAIHealthCoach.Domain.UserProfiles.DietaryPreferences", "DietaryPreferences", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Allergies")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasDefaultValue("")
                                .HasColumnName("DietaryPreferences_Allergies");

                            b1.Property<string>("DietType")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("DietaryPreferences_DietType");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("DietaryPreferences");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.WeightMeasurement", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.UserProfiles.UserProfile", null)
                        .WithMany("WeightMeasurements")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WeightMeasurements_UserProfiles_UserProfileId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Water.WaterLogEntry", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WaterLogEntries_Users_UserId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Food.FoodItem", b =>
                {
                    b.Navigation("ServingSizes");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Navigation("WeightMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
