// <auto-generated />
using System;
using MAIHealthCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAIHealthCoach.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624135429_AddUserProfileAndWeightMeasurements")]
    partial class AddUserProfileAndWeightMeasurements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("PrimaryGoal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Metric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfiles_UserId");

                    b.ToTable("UserProfiles", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.WeightMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "MeasuredAt")
                        .HasDatabaseName("IX_WeightMeasurements_UserProfileId_MeasuredAt");

                    b.ToTable("WeightMeasurements", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_ClerkUserId");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.UserProfile", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("MAIHealthCoach.Domain.UserProfiles.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfiles_Users_UserId");

                    b.OwnsOne("MAIHealthCoach.Domain.UserProfiles.DietaryPreferences", "DietaryPreferences", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Allergies")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasDefaultValue("")
                                .HasColumnName("DietaryPreferences_Allergies");

                            b1.Property<string>("DietType")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("DietaryPreferences_DietType");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("DietaryPreferences");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.WeightMeasurement", b =>
                {
                    b.HasOne("MAIHealthCoach.Domain.UserProfiles.UserProfile", null)
                        .WithMany("WeightMeasurements")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WeightMeasurements_UserProfiles_UserProfileId");
                });

            modelBuilder.Entity("MAIHealthCoach.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Navigation("WeightMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
